#!/usr/bin/env python3
"""Build the 8x16 console font the stub PROM draws with."""
import sys
from PIL import Image, ImageDraw, ImageFont

W, H = 8, 16
FIRST, LAST = 32, 126
path = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

best = None
for size in range(10, 20):
    f = ImageFont.truetype(path, size)
    if f.getlength("M") <= W:
        best = (size, f)
font = best[1]
print("size", best[0], "advance", font.getlength("M"))

rows = []
for c in range(FIRST, LAST + 1):
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, H - 3), chr(c), font=font, fill=255, anchor="ls")
    for y in range(H):
        bits = 0
        for x in range(W):
            if img.getpixel((x, y)) > 110:
                bits |= 1 << x   # this machine puts the leftmost pixel in the low bit
        rows.append(bits)

with open(sys.argv[1], "w") as f:
    f.write("// generated by tools/mkfont.py -- do not edit\n")
    f.write("// %d characters from %d, %d by %d, one byte a row\n"
            % (LAST - FIRST + 1, FIRST, W, H))
    f.write("static const uint8_t s_font[%d] = {\n" % len(rows))
    for i in range(0, len(rows), 16):
        f.write("\t" + " ".join("0x%02x," % b for b in rows[i:i + 16]) + "\n")
    f.write("};\n")
print("wrote", sys.argv[1], len(rows), "bytes")
